# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: mvn clean install exec:java -Dexec.mainClass="com.lambdatest.InterceptNetwork" -Dexec.classpathScope=test -e
